<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ServiceSeeder extends Seeder
{
    public function run()
    {
        // Clear existing services (optional - be careful!)
        // DB::table('services')->truncate();

        $services = [
            // ========== STANDARD SERVICES (Pay-as-you-go) ==========
            [
                'name' => 'Small Basket - Wash & Fold',
                'description' => 'Perfect for light loads & daily essentials. Professional washing, careful folding, and fresh scent guaranteed.',
                'price' => 8.00,
                'unit' => 'basket',
                'service_type' => 'standard',
                'billing_period' => 'one-time',
                'basket_size' => 5,
                'baskets_per_week' => null,
                'baskets_per_month' => null,
                'ironing_included' => false,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Small Basket - Wash + Iron',
                'description' => 'Light loads with professional ironing. Perfect for shirts and formal wear.',
                'price' => 12.00,
                'unit' => 'basket',
                'service_type' => 'standard',
                'billing_period' => 'one-time',
                'basket_size' => 5,
                'baskets_per_week' => null,
                'baskets_per_month' => null,
                'ironing_included' => true,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Medium Basket - Wash & Fold',
                'description' => 'Most popular choice for students. Great value for regular laundry needs.',
                'price' => 12.00,
                'unit' => 'basket',
                'service_type' => 'standard',
                'billing_period' => 'one-time',
                'basket_size' => 10,
                'baskets_per_week' => null,
                'baskets_per_month' => null,
                'ironing_included' => false,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => true,
                'is_best_value' => false,
                'display_order' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Medium Basket - Wash + Iron',
                'description' => 'Medium load with professional ironing service. Clothes returned pressed and ready to wear.',
                'price' => 18.00,
                'unit' => 'basket',
                'service_type' => 'standard',
                'billing_period' => 'one-time',
                'basket_size' => 10,
                'baskets_per_week' => null,
                'baskets_per_month' => null,
                'ironing_included' => true,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Large Basket - Wash & Fold',
                'description' => 'Perfect for heavy laundry loads and includes light bedding items.',
                'price' => 16.00,
                'unit' => 'basket',
                'service_type' => 'standard',
                'billing_period' => 'one-time',
                'basket_size' => 15,
                'baskets_per_week' => null,
                'baskets_per_month' => null,
                'ironing_included' => false,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Large Basket - Wash + Iron',
                'description' => 'Heavy laundry with complete ironing service. Ideal for families.',
                'price' => 24.00,
                'unit' => 'basket',
                'service_type' => 'standard',
                'billing_period' => 'one-time',
                'basket_size' => 15,
                'baskets_per_week' => null,
                'baskets_per_month' => null,
                'ironing_included' => true,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ========== WEEKLY SUBSCRIPTIONS ==========
            [
                'name' => 'Weekly Basic - Wash & Fold',
                'description' => 'Light user plan - 1 small basket every week. Perfect for individuals.',
                'price' => 15.00,
                'unit' => 'week',
                'service_type' => 'weekly',
                'billing_period' => 'weekly',
                'basket_size' => 5,
                'baskets_per_week' => 1,
                'baskets_per_month' => null,
                'ironing_included' => false,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Weekly Basic - Wash + Iron',
                'description' => 'Light user plan with ironing - 1 small basket weekly.',
                'price' => 22.00,
                'unit' => 'week',
                'service_type' => 'weekly',
                'billing_period' => 'weekly',
                'basket_size' => 5,
                'baskets_per_week' => 1,
                'baskets_per_month' => null,
                'ironing_included' => true,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Weekly Standard - Wash & Fold',
                'description' => 'Most popular weekly plan - 1 medium basket every week. Best value for students.',
                'price' => 25.00,
                'unit' => 'week',
                'service_type' => 'weekly',
                'billing_period' => 'weekly',
                'basket_size' => 10,
                'baskets_per_week' => 1,
                'baskets_per_month' => null,
                'ironing_included' => false,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => true,
                'is_best_value' => false,
                'display_order' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Weekly Standard - Wash + Iron',
                'description' => 'Regular plan with ironing - 1 medium basket weekly.',
                'price' => 35.00,
                'unit' => 'week',
                'service_type' => 'weekly',
                'billing_period' => 'weekly',
                'basket_size' => 10,
                'baskets_per_week' => 1,
                'baskets_per_month' => null,
                'ironing_included' => true,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Weekly Premium',
                'description' => 'Busy student plan - 2 small OR 1 medium basket weekly. Ironing included + priority service.',
                'price' => 35.00,
                'unit' => 'week',
                'service_type' => 'weekly',
                'billing_period' => 'weekly',
                'basket_size' => 10,
                'baskets_per_week' => 2,
                'baskets_per_month' => null,
                'ironing_included' => true,
                'priority_service' => true,
                'bedding_cleaning' => false,
                'turnaround_hours' => 12,
                'is_popular' => false,
                'is_best_value' => true,
                'display_order' => 11,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ========== MONTHLY SUBSCRIPTIONS ==========
            [
                'name' => 'Monthly Basic - Wash & Fold',
                'description' => '4 small baskets per month. Save $14 compared to weekly billing.',
                'price' => 50.00,
                'unit' => 'month',
                'service_type' => 'monthly',
                'billing_period' => 'monthly',
                'basket_size' => 5,
                'baskets_per_week' => null,
                'baskets_per_month' => 4,
                'ironing_included' => false,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Monthly Basic - Wash + Iron',
                'description' => '4 small baskets with ironing per month.',
                'price' => 74.00,
                'unit' => 'month',
                'service_type' => 'monthly',
                'billing_period' => 'monthly',
                'basket_size' => 5,
                'baskets_per_week' => null,
                'baskets_per_month' => 4,
                'ironing_included' => true,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 13,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Monthly Standard - Wash & Fold',
                'description' => 'Core seller - 4 medium baskets per month. 1 free ironing upgrade included.',
                'price' => 85.00,
                'unit' => 'month',
                'service_type' => 'monthly',
                'billing_period' => 'monthly',
                'basket_size' => 10,
                'baskets_per_week' => null,
                'baskets_per_month' => 4,
                'ironing_included' => false,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => false,
                'is_best_value' => true,
                'display_order' => 14,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Monthly Standard - Wash + Iron',
                'description' => '4 medium baskets with full ironing service per month.',
                'price' => 125.00,
                'unit' => 'month',
                'service_type' => 'monthly',
                'billing_period' => 'monthly',
                'basket_size' => 10,
                'baskets_per_week' => null,
                'baskets_per_month' => 4,
                'ironing_included' => true,
                'priority_service' => false,
                'bedding_cleaning' => false,
                'turnaround_hours' => 24,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 15,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Monthly Premium',
                'description' => 'Premium plan - 3 medium baskets + 1 bed blanket cleaning per month. Priority service included.',
                'price' => 95.00,
                'unit' => 'month',
                'service_type' => 'monthly',
                'billing_period' => 'monthly',
                'basket_size' => 10,
                'baskets_per_week' => null,
                'baskets_per_month' => 3,
                'ironing_included' => true,
                'priority_service' => true,
                'bedding_cleaning' => true,
                'turnaround_hours' => 12,
                'is_popular' => true,
                'is_best_value' => false,
                'display_order' => 16,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ========== EXPRESS SERVICES ==========
            [
                'name' => 'Express - Small Basket',
                'description' => 'Fast 12-24 hour turnaround for urgent laundry needs.',
                'price' => 18.00,
                'unit' => 'basket',
                'service_type' => 'express',
                'billing_period' => 'one-time',
                'basket_size' => 5,
                'baskets_per_week' => null,
                'baskets_per_month' => null,
                'ironing_included' => false,
                'priority_service' => true,
                'bedding_cleaning' => false,
                'turnaround_hours' => 12,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 17,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Express - Medium Basket',
                'description' => 'Priority processing with 12-24 hour delivery for medium loads.',
                'price' => 22.00,
                'unit' => 'basket',
                'service_type' => 'express',
                'billing_period' => 'one-time',
                'basket_size' => 10,
                'baskets_per_week' => null,
                'baskets_per_month' => null,
                'ironing_included' => false,
                'priority_service' => true,
                'bedding_cleaning' => false,
                'turnaround_hours' => 12,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 18,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Express - Large Basket',
                'description' => 'Rapid turnaround for large laundry loads. Perfect for emergency situations.',
                'price' => 26.00,
                'unit' => 'basket',
                'service_type' => 'express',
                'billing_period' => 'one-time',
                'basket_size' => 15,
                'baskets_per_week' => null,
                'baskets_per_month' => null,
                'ironing_included' => false,
                'priority_service' => true,
                'bedding_cleaning' => false,
                'turnaround_hours' => 12,
                'is_popular' => false,
                'is_best_value' => false,
                'display_order' => 19,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert all services
        foreach ($services as $service) {
            DB::table('services')->insert($service);
        }

        $this->command->info('Services seeded successfully!');
    }
}